language: node_js
node_js:
- '8'
- '10'
cache: yarn
env:
  global:
    secure: Orp09pqv/2r0tHNcZ7N28rGIPYElR+/Qih6DQ8HClwvsjhJ1kR3Ehvv0s88eku4Ix32FCe6PSzc7r9PrNw/8PAboVUd5c/xtObYX592mQac6JVjk2JAr8kdyXVuWnWU2MjAQrwTkSi/HJ0OA+I4FC0gPWL1ImuAHw69102quv4kl5eAyV8ODNoXZJttSuy+2sgflM655NB8Ernfh7DXc7o9s7fOxMm5J8mvIp4EyjA9PntrISE4Bfdy0eyxBiU1TlZTPtq4s0rOxp0kLYgiPxNQj8elBQ85xEOJcb8P/XQyxVhyvB01o9z+Mu3IInuuvhm0CInO9O6Qcp9p126BxlVJTVV4NY+KZBFBW60wID0ereCqq/hZnjJfJXV2eUjFpDMHBT1LgLnZrsTXnFzHIu/83mT9cYTzqrlknzBQc8pg6/8P7c39e4lnlzXiJ4ttcfAV6mY4csSSWE755UcnbfmcHPMzkC5Rznzk47K0KUqzC5s6gMbd7pTlmZkOfComvUudH1iflpLminbraAzXNYBTurpOSgWcH9jNLksoUmhhqinxzGU6AoGM1f9R1kALpAnnn4WTLz0nU4I9zi52LYAjSsXjdlm9IttdKsi2QBWqIuUxaa1Jwu6vMP1Th8KbZbfyqeL+BaLjTTr4+nfQOSKk6T+JlTE5/wLQvsCKMlnU=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: hello@rplan.com
  api_key:
    secure: Ub4GNS3Xzq8ZWERdsAEfA5+pXBJWnZjWvprBF9IchjNMRCYreRQDZXh4G6aXAbaF4u5RqAwDIcQt5qLQ6A8/tgG3AVz1GyKKK/5iQjmyvOJ0tKT4Klsr6SdMaE++0g90gPZGFcb7mKXtlMmyqWnwSddC+qf3wOJs6u035xZJYooCNyKCfQnu7T1OazWBUvifX7ET1hyKkXQmW9urD2sOfFaoWKoPYMTUiYUr6Hlz1Z7RcpD5aHWG3n44OQW2pjvk/nb7j9FhCdapgcFcLpBDjn7FRCZmxFAfQS2D2okd7NINx3c3oVGyod3uvXP19647KX/x9ALaX5dt8hFu3+mAAsK5V1E7lq882dc0QQ1fN+dZWLCmk5S/OHwkYB30S7rYM8Xn79HBb1uGC+nlSY/K26SYAl2iHCJT8qxS/MTZdRC4xk/gvHk486IeTcfkfk9bHxjncyuujY3Pjzmo6ojyPPBz3kFPtkRJ7qSOJHZovL9p17pZXyMRMt3Hr+XZfhxeDtQFx8VmnJJm+lMRHwmlvejj6U3HFoC7V3HJNRjAKq67AfBkvqfh13Nhj4qX1OmWvUdYFAA8TLyIZtnh1JVVDm0I9srebJLi8P5yeZ3FveijJM+aGgLovLjOi+qcRkBpvpLoD1gRyBXK9WMU3HxTLjEgavfY3n/8dXuq9rUC+yk=
  on:
    tags: true
    repo: actano/borders-key-value
    node: '8'
