language: node_js
node_js:
- '8'
- '10'
cache: yarn
env:
  global:
    secure: Orp09pqv/2r0tHNcZ7N28rGIPYElR+/Qih6DQ8HClwvsjhJ1kR3Ehvv0s88eku4Ix32FCe6PSzc7r9PrNw/8PAboVUd5c/xtObYX592mQac6JVjk2JAr8kdyXVuWnWU2MjAQrwTkSi/HJ0OA+I4FC0gPWL1ImuAHw69102quv4kl5eAyV8ODNoXZJttSuy+2sgflM655NB8Ernfh7DXc7o9s7fOxMm5J8mvIp4EyjA9PntrISE4Bfdy0eyxBiU1TlZTPtq4s0rOxp0kLYgiPxNQj8elBQ85xEOJcb8P/XQyxVhyvB01o9z+Mu3IInuuvhm0CInO9O6Qcp9p126BxlVJTVV4NY+KZBFBW60wID0ereCqq/hZnjJfJXV2eUjFpDMHBT1LgLnZrsTXnFzHIu/83mT9cYTzqrlknzBQc8pg6/8P7c39e4lnlzXiJ4ttcfAV6mY4csSSWE755UcnbfmcHPMzkC5Rznzk47K0KUqzC5s6gMbd7pTlmZkOfComvUudH1iflpLminbraAzXNYBTurpOSgWcH9jNLksoUmhhqinxzGU6AoGM1f9R1kALpAnnn4WTLz0nU4I9zi52LYAjSsXjdlm9IttdKsi2QBWqIuUxaa1Jwu6vMP1Th8KbZbfyqeL+BaLjTTr4+nfQOSKk6T+JlTE5/wLQvsCKMlnU=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: rplan-ci@actano.de
  api_key:
    secure: ZCBP3n2egcooRHR2JV4HUftDjhvo0uKicVk64ZDlxeeAf4dK0RAS2z5WTRt5rxeW9gXZTBQcBRwbfuZeU0vlZd/D4tt//qMgB92bMaChbLqW9MS0zNIDaQ90Rp4YXoW74LGjsEdHCfN6gRwP3y+PrypdUBoBHcWfjdDhbDFZJMMka+Ub2xWfZFRXAojRM1eMxz4PTte6R2ddOwyR84yVmMsUDmaA9+AIQonWCaBrOyO6aJr7kSOzuC52a4DonxnYRgsLxHNn8EEKHwiHPzxcpi1qXzL6iWHgvnQQ6ycL5OMAhI5vi1MwQumRoSIdu6c2lqkMyLJshm0UyKK1FtWC/xfbdVSzVDwDodYSf8fM/izHIQ79SjTEcbioB4r8RzjWReesVher2ccpPwTML9Sn6zRw4QdaAuf6wwvVnIXC7QYrBmf5W9cO3w7QOtMj6fzIaes6FROZJOaamuM2eHXBkLZk3KMu/2+3TcVMOpmtfHzvuU1GmXavumTofVT2ePs5X9WkgwGkR0n5sBtMAPSbIoQpu2SfWBygSbTcl3EMSYUUquUgRb+sju5BWYLCKfpka4Kf9U/OYqEEc1ine9pG9HzQDAukjACLeSXIUQb1sy2inzhwRRkvjXh39X8z8hUfYtfNwobMOGOWcTHRAO5M8+SH0b/lB8cYAlR1mSMvRUc=
  on:
    tags: true
    repo: actano/borders-key-value
    node: '8'
