export { default as get, TYPE as GET } from './get'
export { default as insert, TYPE as INSERT } from './insert'
export { default as remove, TYPE as REMOVE } from './remove'
export { default as replace, TYPE as REPLACE } from './replace'
export { default as upsert, TYPE as UPSERT } from './upsert'
export { default as cached, TYPE as CACHED } from './cached'
export { default as cacheStats, TYPE as CACHE_STATS } from './cache-stats'
